import type { ClinicalCase, Notification, AnalyticsData, User } from "@/types";

export const mockUser: User = {
  id: "u1",
  name: "Dr. Priya Sharma",
  email: "priya.sharma@oncology.com",
  role: "doctor",
  hospital: "AIIMS New Delhi",
  specialization: "Medical Oncology",
  createdAt: "2024-01-15T10:00:00Z",
};

export const mockCases: ClinicalCase[] = [
  {
    id: "c001",
    patientName: "Ananya Verma",
    patientAge: 48,
    patientSex: "Female",
    patientContact: "+91-9876543210",
    doctorNotes: "Family history of breast cancer. BRCA testing ordered.",
    tumour: {
      stage: "II",
      grade: 2,
      sizeInCm: 2.3,
      lymphNodesPositive: true,
      lymphNodeCount: 3,
      histologyType: "Invasive Ductal Carcinoma",
    },
    biomarkers: {
      er: "Positive",
      pr: "Positive",
      her2: "Negative",
      ki67: 12,
      pdl1: "Unknown",
      brca1: "Negative",
      brca2: "Negative",
      pik3ca: "Positive",
      cyclinD1: "Positive",
      tp53: "Negative",
      top2a: "Unknown",
      bcl2: "Positive",
      tils: 15,
      oncotypeDX: 18,
      mammaPrint: "Low Risk",
      pam50: "Luminal A",
    },
    healthProfile: {
      lvef: 62,
      comorbidities: ["Hypertension"],
      medications: ["Amlodipine 5mg"],
      allergies: ["Penicillin"],
      menopausalStatus: "Post",
      performanceScore: 0,
    },
    subtype: "Luminal A",
    status: "Treatment Ongoing",
    createdAt: "2025-12-10T09:00:00Z",
    updatedAt: "2026-01-15T14:30:00Z",
    doctorId: "u1",
    recommendations: [
      {
        id: "r1",
        name: "Endocrine Therapy: Letrozole + CDK4/6 Inhibitor",
        description: "First-line endocrine therapy with CDK4/6 inhibitor for HR+/HER2- post-menopausal metastatic breast cancer.",
        confidenceScore: 94,
        guidelineSource: "NCCN",
        ruleTrace: [
          { id: "n1", label: "ER Status", value: "Positive", conclusion: "Endocrine responsive" },
          { id: "n2", label: "PR Status", value: "Positive", conclusion: "Higher endocrine sensitivity" },
          { id: "n3", label: "HER2 Status", value: "Negative", conclusion: "No targeted HER2 therapy needed" },
          { id: "n4", label: "Ki-67", value: "12%", conclusion: "Low proliferation risk" },
          { id: "n5", label: "Menopausal", value: "Post", conclusion: "Aromatase inhibitor eligible" },
        ],
        duration: "5 years",
        sideEffectSeverity: 2,
        suitabilityPercent: 94,
        isTopRecommendation: true,
      },
      {
        id: "r2",
        name: "Tamoxifen Monotherapy",
        description: "Alternative endocrine therapy for HR+ patients, especially in resource-limited settings.",
        confidenceScore: 78,
        guidelineSource: "ISMPO",
        ruleTrace: [
          { id: "n6", label: "ER Status", value: "Positive", conclusion: "Tamoxifen eligible" },
          { id: "n7", label: "Oncotype DX", value: "18", conclusion: "Intermediate risk — endocrine therapy only" },
        ],
        duration: "5-10 years",
        sideEffectSeverity: 2,
        suitabilityPercent: 78,
      },
    ],
    safetyAlerts: [
      {
        id: "a1",
        severity: "Medium",
        triggerSource: "PIK3CA Mutation",
        affectedTreatment: "CDK4/6 Inhibitor",
        recommendedAction: "Consider PI3K inhibitor alpelisib combination",
        description: "PIK3CA mutation detected — may indicate resistance to CDK4/6 inhibitors. Monitor for response.",
      },
    ],
    versions: [
      {
        id: "v1",
        version: 1,
        createdAt: "2025-12-10T09:00:00Z",
        doctorName: "Dr. Priya Sharma",
        changeSummary: "Initial case created with pathology report",
        snapshot: {},
      },
      {
        id: "v2",
        version: 2,
        createdAt: "2025-12-20T11:00:00Z",
        doctorName: "Dr. Priya Sharma",
        changeSummary: "Added Oncotype DX score 18, updated Ki-67 from 14% to 12%",
        snapshot: {},
      },
    ],
  },
  {
    id: "c002",
    patientName: "Meena Iyer",
    patientAge: 55,
    patientSex: "Female",
    doctorNotes: "Aggressive subtype, BRCA2 positive — PARP inhibitor evaluation.",
    tumour: {
      stage: "III",
      grade: 3,
      sizeInCm: 4.1,
      lymphNodesPositive: true,
      lymphNodeCount: 7,
      histologyType: "Invasive Ductal Carcinoma",
    },
    biomarkers: {
      er: "Negative",
      pr: "Negative",
      her2: "Negative",
      ki67: 45,
      pdl1: "Positive",
      brca1: "Negative",
      brca2: "Positive",
      pik3ca: "Negative",
      cyclinD1: "Negative",
      tp53: "Positive",
      top2a: "Positive",
      bcl2: "Negative",
      tils: 40,
      mammaPrint: "High Risk",
    },
    healthProfile: {
      lvef: 58,
      comorbidities: ["Diabetes"],
      medications: ["Metformin 500mg"],
      allergies: [],
      menopausalStatus: "Post",
      performanceScore: 1,
    },
    subtype: "TNBC",
    status: "Under Analysis",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
    doctorId: "u1",
    recommendations: [],
    safetyAlerts: [],
  },
  {
    id: "c003",
    patientName: "Raj Kumar",
    patientAge: 42,
    patientSex: "Male",
    tumour: { stage: "I", grade: 2, sizeInCm: 1.2, lymphNodesPositive: false, histologyType: "Invasive Lobular" },
    biomarkers: {
      er: "Positive", pr: "Negative", her2: "Positive",
      ki67: 28, pdl1: "Unknown", brca1: "Unknown", brca2: "Unknown",
      pik3ca: "Unknown", cyclinD1: "Positive", tp53: "Unknown", top2a: "Positive",
      bcl2: "Negative", tils: 10, mammaPrint: "High Risk",
    },
    healthProfile: { lvef: 67, comorbidities: [], medications: [], allergies: ["Sulfa drugs"] },
    subtype: "HER2-Enriched",
    status: "Pending Review",
    createdAt: "2026-02-01T08:30:00Z",
    updatedAt: "2026-02-05T16:00:00Z",
    doctorId: "u1",
    recommendations: [],
    safetyAlerts: [],
  },
  {
    id: "c004",
    patientName: "Sunita Patel",
    patientAge: 61,
    patientSex: "Female",
    tumour: { stage: "II", grade: 2, sizeInCm: 3.0, lymphNodesPositive: true, lymphNodeCount: 2, histologyType: "Invasive Ductal Carcinoma" },
    biomarkers: {
      er: "Positive", pr: "Positive", her2: "Positive",
      ki67: 22, pdl1: "Unknown", brca1: "Negative", brca2: "Negative",
      pik3ca: "Positive", cyclinD1: "Positive", tp53: "Negative", top2a: "Unknown",
      bcl2: "Positive", oncotypeDX: 24, mammaPrint: "High Risk",
    },
    healthProfile: { lvef: 60, comorbidities: ["Cardiac", "Hypertension"], medications: ["Bisoprolol 2.5mg", "Ramipril 5mg"], allergies: [] },
    subtype: "Luminal B",
    status: "Completed",
    createdAt: "2025-11-05T11:00:00Z",
    updatedAt: "2025-12-20T09:00:00Z",
    doctorId: "u1",
    recommendations: [],
    safetyAlerts: [],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "alert",
    title: "Safety Alert — Meena Iyer",
    message: "BRCA2 mutation detected. PARP inhibitor eligibility assessment required.",
    caseId: "c002",
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "n2",
    type: "analysis",
    title: "Analysis Complete — Meena Iyer",
    message: "NLP extraction and subtype classification completed. Treatment suggestions ready.",
    caseId: "c002",
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "n3",
    type: "case_update",
    title: "Case Updated — Ananya Verma",
    message: "Oncotype DX score updated from 21 to 18. Recommendations recalculated.",
    caseId: "c001",
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "n4",
    type: "second_opinion",
    title: "Second Opinion Requested — Raj Kumar",
    message: "Dr. Anil Mehta has requested a second opinion on the HER2+ treatment plan.",
    caseId: "c003",
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: "n5",
    type: "case_update",
    title: "Treatment Started — Sunita Patel",
    message: "Letrozole + Palbociclib regime started. Next follow-up in 3 weeks.",
    caseId: "c004",
    isRead: true,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: "n6",
    type: "alert",
    title: "Cardiac Risk Flag — Sunita Patel",
    message: "LVEF borderline at 60%. Cardiology consult recommended before anthracycline.",
    caseId: "c004",
    isRead: true,
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
];

export const mockAnalytics: AnalyticsData = {
  subtypeDistribution: { "Luminal A": 42, "Luminal B": 28, "HER2-Enriched": 15, "TNBC": 12, "Unknown": 3 },
  casesByStage: { I: 18, II: 35, III: 32, IV: 15 },
  biomarkerPositivity: {
    ER: 72, PR: 64, HER2: 24, "Ki-67": 48, "PD-L1": 22,
    BRCA1: 8, BRCA2: 12, PIK3CA: 38, TP53: 35, TOP2A: 28,
  },
  monthlyVolume: [
    { month: "Sep", cases: 24 }, { month: "Oct", cases: 31 }, { month: "Nov", cases: 28 },
    { month: "Dec", cases: 35 }, { month: "Jan", cases: 42 }, { month: "Feb", cases: 38 },
    { month: "Mar", cases: 45 },
  ],
  treatmentFrequency: {
    "Endocrine + CDK4/6": 38, "Chemotherapy": 28, "Trastuzumab": 18,
    "PARP Inhibitor": 8, "Immunotherapy": 5, "Other": 3,
  },
  alertFrequency: [
    { type: "Cardiac Risk", count: 18 }, { type: "Drug Interaction", count: 14 },
    { type: "Contraindication", count: 22 }, { type: "BRCA Alert", count: 10 },
    { type: "Resistance Signal", count: 9 }, { type: "Dose Adjustment", count: 16 },
  ],
};
